#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MATRIX_WORKFLOW="$ROOT_DIR/.github/workflows/matrix-updater.yml"
AUTOFIX_WORKFLOW="$ROOT_DIR/.github/workflows/sentinel-autofix.yml"
AUTO_FIX_SCRIPT="$ROOT_DIR/scripts/auto-fix.sh"
CLIENT_SCRIPT="$ROOT_DIR/scripts/llm-message-client.sh"
CLAUDE_DOC="$ROOT_DIR/CLAUDE.md"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_file_contains() {
  local file="$1"
  local needle="$2"
  if ! grep -Fq -- "$needle" "$file"; then
    fail "$file must contain: $needle"
  fi
}

assert_file_not_contains() {
  local file="$1"
  local needle="$2"
  if grep -Fq -- "$needle" "$file"; then
    fail "$file must not contain: $needle"
  fi
}

for file in "$MATRIX_WORKFLOW" "$AUTOFIX_WORKFLOW" "$AUTO_FIX_SCRIPT" "$CLAUDE_DOC"; do
  [ -f "$file" ] || fail "Missing expected file: $file"
done

[ -f "$CLIENT_SCRIPT" ] || fail "Missing shared LLM client: $CLIENT_SCRIPT"

assert_file_contains "$MATRIX_WORKFLOW" "llm_provider:"
assert_file_contains "$MATRIX_WORKFLOW" "SENTINEL_LLM_PROVIDER:"
assert_file_contains "$MATRIX_WORKFLOW" "HEIYUCODE_AUTH_TOKEN:"
assert_file_contains "$MATRIX_WORKFLOW" "HEIYUCODE_API_KEY:"
assert_file_contains "$MATRIX_WORKFLOW" "HEIYUCODE_BASE_URL:"
assert_file_contains "$MATRIX_WORKFLOW" "HEIYUCODE_MODEL:"
assert_file_contains "$MATRIX_WORKFLOW" "bash scripts/llm-message-client.sh"
assert_file_not_contains "$MATRIX_WORKFLOW" "https://api.anthropic.com/v1/messages"

assert_file_contains "$AUTOFIX_WORKFLOW" "llm_provider:"
assert_file_contains "$AUTOFIX_WORKFLOW" "SENTINEL_LLM_PROVIDER:"
assert_file_contains "$AUTOFIX_WORKFLOW" "HEIYUCODE_AUTH_TOKEN:"
assert_file_contains "$AUTOFIX_WORKFLOW" "HEIYUCODE_API_KEY:"
assert_file_contains "$AUTOFIX_WORKFLOW" "HEIYUCODE_BASE_URL:"
assert_file_contains "$AUTOFIX_WORKFLOW" "HEIYUCODE_MODEL:"

assert_file_contains "$AUTO_FIX_SCRIPT" "llm-message-client.sh"
assert_file_not_contains "$AUTO_FIX_SCRIPT" "ANTHROPIC_API_KEY not set -- cannot generate fixes"
assert_file_not_contains "$AUTO_FIX_SCRIPT" "https://api.anthropic.com/v1/messages"
assert_file_not_contains "$AUTO_FIX_SCRIPT" "Generated by Claude API"

assert_file_contains "$CLIENT_SCRIPT" "SENTINEL_LLM_PROVIDER"
assert_file_contains "$CLIENT_SCRIPT" "HEIYUCODE_AUTH_TOKEN"
assert_file_contains "$CLIENT_SCRIPT" "HEIYUCODE_API_KEY"
assert_file_contains "$CLIENT_SCRIPT" "Authorization: Bearer"
assert_file_contains "$CLIENT_SCRIPT" "x-api-key"
assert_file_contains "$CLIENT_SCRIPT" "https://api.anthropic.com/v1/messages"

assert_file_contains "$CLAUDE_DOC" "llm-message-client.sh"
assert_file_contains "$CLAUDE_DOC" "LLM provider router"
assert_file_not_contains "$CLAUDE_DOC" "LLM 一致性审查（Claude API）"

ruby -e 'require "yaml"; ARGV.each { |file| YAML.load_file(file) }' \
  "$MATRIX_WORKFLOW" \
  "$AUTOFIX_WORKFLOW"

echo "auxiliary LLM workflow shape test passed"
