name: Trigger Test
on:
  workflow_dispatch:
    inputs:
      msg:
        description: test
        required: false
        default: hello
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger test success"
